FROM node:18-alpine as build
ENV NODE_ENV=production

WORKDIR /app

COPY ["package.json", "package-lock.json*", "./"]
RUN npm ci --silent
RUN npm install react-scripts@5.0.1 -g --silent

COPY . .
RUN npm run build
RUN npm install serve -g
CMD [ "serve", "-s", "build" ]